version: "3.9"
services:
#  tor:
#    build:
#      context: ./
#      dockerfile: tor/Dockerfile
  haproxy:
    network_mode: "host"
    build:
      context: ./
      dockerfile: haproxy/Dockerfile
    ports:
      - 80:80 #http
      - 2000:2000 #port 2000 haproxy socket for external management
    volumes:
      - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg
      - ./haproxy/ddos.map:/etc/haproxy/ddos.map
      - ./haproxy/hosts.map:/etc/haproxy/hosts.map
      - ./haproxy/backends.map:/etc/haproxy/backends.map
      - ./haproxy/blocked.map:/etc/haproxy/blocked.map
      - ./haproxy/whitelist.map:/etc/haproxy/whitelist.map
      - ./haproxy/maintenance.map:/etc/haproxy/maintenance.map
      - ./haproxy/dataplaneapi.hcl:/etc/haproxy/dataplaneapi.hcl
      - ./haproxy/trace.txt:/etc/haproxy/trace.txt
      - ./src/scripts/:/etc/haproxy/scripts/
      - ./src/libs/:/etc/haproxy/libs/
      - ./haproxy/js/:/var/www/js/
    environment:
      - RECAPTCHA_SECRET=
      - RECAPTCHA_SITEKEY=
      - CAPTCHA_COOKIE_SECRET=changeme
      - POW_COOKIE_SECRET=changeme
      - RAY_ID=docker
      - BUCKET_DURATION=43200
      - BACKEND_NAME=servers
      - SERVER_PREFIX=websrv
  nginx:
    ports:
      - 81:80
    image: "nginx:latest"
    volumes:
      - ./nginx:/usr/share/nginx/html
