version: "3.9"
services:
  haproxy:
    build:
      context: ./
      dockerfile: haproxy/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./src/scripts/:/usr/local/etc/haproxy/scripts/
      - ./src/libs/:/usr/local/etc/haproxy/libs/
    environment:
      - HCAPTCHA_SECRET=
      - HCAPTCHA_SITEKEY=
      - CAPTCHA_COOKIE_SECRET=
      - POW_COOKIE_SECRET=
  nginx:
    image: "nginx:latest"
    volumes:
      - ./js:/usr/share/nginx/html
