version: "3.9"
services:
#  tor:
#    build:
#      context: ./
#      dockerfile: tor/Dockerfile
  haproxy:
    build:
      context: ./
      dockerfile: haproxy/Dockerfile
    ports:
      - 80:80 #http
      - 2000:2000 #port 2000 haproxy socket for external management
    volumes:
      - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg
      - ./haproxy/ddos.map:/etc/haproxy/ddos.map
      - ./haproxy/hosts.map:/etc/haproxy/hosts.map
      - ./src/scripts/:/etc/haproxy/scripts/
      - ./src/libs/:/etc/haproxy/libs/
      - ./haproxy/js/:/var/www/js/
    environment:
      - HCAPTCHA_SECRET=
      - HCAPTCHA_SITEKEY=
      - CAPTCHA_COOKIE_SECRET=
      - POW_COOKIE_SECRET=
      - RAY_ID=
      - BUCKET_DURATION=43200
  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx:/usr/share/nginx/html
